# -*- coding: utf-8 -*-
"""fraudDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BgAKEpY8ba8d-JOqin26ExuJ89CRviY
"""

import pandas as pd # Import the pandas library for data manipulation and analysis.
import numpy as np # Import the numpy library for numerical operations.
import matplotlib.pyplot as plt # Import the matplotlib.pyplot library for creating static, interactive, and animated visualizations.
df=pd.read_csv("creditcard.csv") # Load the "creditcard.csv" file into a pandas DataFrame named 'df'.
df.head(5) # Display the first 5 rows of the DataFrame to get a quick overview of the data.

print(df.shape) # Print the dimensions (number of rows, number of columns) of the DataFrame.
print(df.dtypes) # Print the data types of each column in the DataFrame.
print(df.isnull().sum().max()) # Check for missing values: calculate the sum of nulls for each column and then find the maximum among these sums. A result of 0 indicates no missing values.
print(df['Class'].value_counts(),"fraud fraction",df['Class'].mean()) # Print the count of each unique value in the 'Class' column (to see the distribution of fraudulent vs. non-fraudulent transactions) and calculate the fraction of fraudulent transactions (mean of 'Class' column).

from sklearn.preprocessing import StandardScaler # Import StandardScaler for feature scaling.
from sklearn.decomposition import PCA # Import PCA for dimensionality reduction.
from sklearn.manifold import TSNE # Import TSNE for non-linear dimensionality reduction (though not used in this specific cell).

cols = [c for c in df.columns if c not in ['Time','Class']] # Create a list of column names, excluding 'Time' and 'Class' (target variable).
x=df[cols].values # Extract the feature columns into a NumPy array 'x'.
y=df['Class'].values # Extract the 'Class' column (target variable) into a NumPy array 'y'.
x_scaled=StandardScaler().fit_transform(x) # Scale the features using StandardScaler to have zero mean and unit variance.

#PCA
idx=np.random.RandomState(0).choice(len(x_scaled),size=min(10000,len(x_scaled)),replace=False) # Randomly select a subset of indices for PCA to speed up computation on large datasets.
x_pca=PCA(n_components=2).fit_transform(x_scaled[idx]) # Apply PCA to reduce the scaled features to 2 principal components for visualization.
plt.scatter(x_pca[:,0],x_pca[:,1],s=6,c=y[idx]) # Create a scatter plot of the two principal components, colored by the 'Class' label.
plt.title("PCA 2D chart") # Set the title of the plot.
plt.show # Display the plot.

# t-SNE (on very small sample)
idx2 = np.random.RandomState(1).choice(len(x_scaled), size=2000, replace=False) # Randomly select a smaller subset of 2000 indices for t-SNE due to its computational intensity.
# Note: X_tsne is not defined here. It seems like the t-SNE transformation was intended but not executed or stored in X_tsne.
# Assuming X_tsne was computed in a previous step, this line would plot the t-SNE results.
plt.scatter(X_tsne[:,0], X_tsne[:,1], s=8, c=y[idx2]) # Create a scatter plot of the t-SNE components, colored by the 'Class' label.
plt.title("t-SNE (small sample)") # Set the title of the plot.
plt.show() # Display the plot.

from sklearn.model_selection import train_test_split # Import train_test_split for splitting data into training and testing sets.
from sklearn.preprocessing import StandardScaler # Import StandardScaler for feature scaling.

# Separate features and labels
X = df.drop(columns=['Class']) # Create feature set 'X' by dropping the 'Class' column from the DataFrame.
y = df['Class'] # Create target variable 'y' with the 'Class' column.

# Scale features
scaler = StandardScaler() # Initialize StandardScaler.
X_scaled = scaler.fit_transform(X) # Fit the scaler to the features and transform them to have zero mean and unit variance.

# Train-test split (stratified to preserve fraud ratio)
X_train, X_test, y_train, y_test = train_test_split( # Split the scaled features and target variable into training and testing sets.
    X_scaled, y, test_size=0.25, stratify=y, random_state=42 # Use 25% of the data for testing, stratify by 'y' to maintain class distribution, and set a random state for reproducibility.
)

from sklearn.metrics import ( # Import various metrics from sklearn.metrics for model evaluation.
    roc_auc_score, # Import ROC AUC score for evaluating binary classifiers.
    average_precision_score, # Import Average Precision score for evaluating binary classifiers, especially useful for imbalanced datasets.
    classification_report, # Import classification_report to display precision, recall, f1-score, and support for each class.
    confusion_matrix # Import confusion_matrix to evaluate the performance of a classification model.
)
import numpy as np # Import the numpy library for numerical operations.

from sklearn.ensemble import IsolationForest # Import IsolationForest, an anomaly detection algorithm.

iso = IsolationForest( # Initialize the IsolationForest model.
    n_estimators=200, # Set the number of base estimators (trees) to 200.
    contamination=y_train.mean(), # Estimate the proportion of outliers in the data, using the fraud fraction from the training set.
    random_state=42 # Set the random state for reproducibility.
)
iso.fit(X_train) # Fit the IsolationForest model to the training data. This step builds the ensemble of isolation trees.

iso_scores = -iso.decision_function(X_test)  # Calculate anomaly scores for the test set. Higher scores indicate a higher likelihood of being anomalous (fraudulent). The negative sign is used because `decision_function` returns lower values for anomalies.
iso_auc = roc_auc_score(y_test, iso_scores) # Calculate the Area Under the Receiver Operating Characteristic Curve (ROC AUC) for Isolation Forest.
iso_ap = average_precision_score(y_test, iso_scores) # Calculate the Average Precision (AP) score for Isolation Forest.

print("Isolation Forest ROC-AUC:", iso_auc) # Print the calculated ROC AUC score.
print("Isolation Forest AP:", iso_ap) # Print the calculated Average Precision score.

threshold = np.percentile(iso_scores, 99.8) # Determine a threshold for anomaly detection by taking the 99.8th percentile of the anomaly scores. Scores above this threshold will be classified as anomalies.
iso_pred = (iso_scores >= threshold).astype(int) # Classify instances as fraudulent (1) if their anomaly score is greater than or equal to the threshold, and non-fraudulent (0) otherwise.

print(confusion_matrix(y_test, iso_pred)) # Print the confusion matrix to evaluate the performance of the Isolation Forest model's binary classification.
print(classification_report(y_test, iso_pred, digits=4)) # Print a detailed classification report including precision, recall, f1-score, and support for each class, with 4 decimal places.

k = 100 # Define 'k' as the number of top anomalous instances to consider.
top_k_idx = np.argsort(iso_scores)[-k:] # Get the indices of the 'k' instances with the highest anomaly scores (most anomalous).
precision_at_100 = y_test.iloc[top_k_idx].sum() / k # Calculate Precision@100: the proportion of actual fraudulent cases among the top 'k' instances identified as anomalous.
print("Isolation Forest Precision@100:", precision_at_100) # Print the calculated Precision@100.

from sklearn.neighbors import LocalOutlierFactor # Import LocalOutlierFactor (LOF), another anomaly detection algorithm.

lof = LocalOutlierFactor( # Initialize the LocalOutlierFactor model.
    n_neighbors=20, # Set the number of neighbors to consider for local density estimation to 20.
    contamination=y_train.mean() # Estimate the proportion of outliers in the data, using the fraud fraction from the training set.
) # Note: LOF is typically unsupervised, but contamination can be used to set a threshold for decision_function.

lof_pred = lof.fit_predict(X_test) # Fit the LOF model to the test data and predict outlier labels (-1 for outlier, 1 for inlier).
lof_scores = -lof.negative_outlier_factor_ # Calculate anomaly scores. Lower negative_outlier_factor_ values indicate higher anomaly likelihood, so we negate it to get higher scores for anomalies.

lof_auc = roc_auc_score(y_test, lof_scores) # Calculate the ROC AUC score for LOF.
lof_ap = average_precision_score(y_test, lof_scores) # Calculate the Average Precision score for LOF.

print("LOF ROC-AUC:", lof_auc) # Print the calculated LOF ROC AUC score.
print("LOF AP:", lof_ap) # Print the calculated LOF Average Precision score.

lof_binary = (lof_pred == -1).astype(int) # Convert LOF predictions to binary: 1 for outliers (-1) and 0 for inliers (1).
print(confusion_matrix(y_test, lof_binary)) # Print the confusion matrix for LOF's binary classification.
print(classification_report(y_test, lof_binary, digits=4)) # Print a detailed classification report for LOF, with 4 decimal places.

from sklearn.svm import OneClassSVM # Import OneClassSVM for unsupervised anomaly detection.

# Use smaller subset (important)
X_train_small = X_train[:20000] # Create a smaller training subset for OneClassSVM due to its computational cost.
X_test_small = X_test[:10000] # Create a smaller testing subset for OneClassSVM.
y_test_small = y_test.iloc[:10000] # Create a corresponding smaller target variable subset for testing.

ocsvm = OneClassSVM( # Initialize the OneClassSVM model.
    nu=y_train.mean(), # Set the upper bound on the fraction of training errors and a lower bound of the fraction of support vectors, using the fraud fraction from the training set.
    kernel='rbf', # Use the Radial Basis Function (RBF) kernel.
    gamma='auto' # Set the kernel coefficient for 'rbf' to 'auto', which uses 1 / (n_features * X.var()).
)

ocsvm.fit(X_train_small) # Fit the OneClassSVM model to the small training subset. This learns the boundary of the 'normal' data.
svm_scores = -ocsvm.decision_function(X_test_small) # Calculate anomaly scores for the small test set. Lower `decision_function` values indicate higher anomaly likelihood, so we negate it.

print("OCSVM ROC-AUC:", roc_auc_score(y_test_small, svm_scores)) # Print the ROC AUC score for OneClassSVM on the small test set.
print("OCSVM AP:", average_precision_score(y_test_small, svm_scores)) # Print the Average Precision score for OneClassSVM on the small test set.

from tensorflow.keras import layers, models # Import layers and models from TensorFlow Keras for building neural networks.

input_dim = X_train.shape[1] # Get the number of features (columns) in the training data, which will be the input dimension for the autoencoder.

model = models.Sequential([ # Initialize a Sequential model for building the autoencoder layer by layer.
    layers.Dense(64, activation='relu', input_shape=(input_dim,)), # Add the first dense (fully connected) layer with 64 units, ReLU activation, and specify the input shape.
    layers.Dense(32, activation='relu'), # Add a second dense layer with 32 units and ReLU activation (encoder part).
    layers.Dense(64, activation='relu'), # Add a third dense layer with 64 units and ReLU activation (decoder part).
    layers.Dense(input_dim) # Add the output dense layer with the same number of units as the input dimension, to reconstruct the original input.
])

model.compile(optimizer='adam', loss='mse') # Compile the model: use the Adam optimizer and Mean Squared Error (MSE) as the loss function, as this is a reconstruction task.
model.fit(X_train, X_train, epochs=20, batch_size=256, validation_split=0.1) # Train the autoencoder: fit the model on the training data, using X_train as both input and target for reconstruction. Train for 20 epochs with a batch size of 256, and use 10% of the training data for validation.

recon = model.predict(X_test) # Use the trained autoencoder to predict (reconstruct) the test data.
recon_error = np.mean((X_test - recon) ** 2, axis=1) # Calculate the reconstruction error for each instance in the test set. This is typically the mean squared error between the original and reconstructed data.

print("Autoencoder ROC-AUC:", roc_auc_score(y_test, recon_error)) # Print the ROC AUC score, evaluating the autoencoder's ability to distinguish between normal and fraudulent transactions based on reconstruction error.
print("Autoencoder AP:", average_precision_score(y_test, recon_error)) # Print the Average Precision score, providing another metric for anomaly detection performance.

